formancehq/ledger

- cmd/ui.go
- config/config.go
> Fix ui open on linux server distributions

- cmd/ui.go
- config/config.go
Implements #24 
**With env**
```
NUMARY_UI_HTTP_BIND_ADDRESS=localhost:3070 \
numary ui
```
**With config file**
```
ui:
http:
bind_address: localhost:3070
```
> Move ui http bind address in config

- api/http.go
- cmd/root.go
* Adds a check command to verify validity of a script
* Adds an `details` field to /script api responses in case of an error, with a url to the numscript playground showing the formatted error
> Check command and error details

- .github/workflows/pr_open.yml
- storage/postgres/transactions.go
Signed-off-by: Maxence Maireaux <maxence@maireaux.fr>
> Add PGSQL in Test

- api/controllers/transaction_controller.go
Add account query parameter to filter transactions,
I don't see strong testing, is there a plan to increase coverage?
Thanks!
> add account to query

- .github/workflows/pr_open.yml
- go.mod
- go.sum
Signed-off-by: Maxence Maireaux <maxence@maireaux.fr>
> Add v1.0.0 for Machine deps

- .github/workflows/release.yml
Signed-off-by: Maxence Maireaux <maxence@maireaux.fr>
> Remove Readme.io

- .github/.goreleaser.default.yml
- .github/.goreleaser.windows.yml
Signed-off-by: Maxence Maireaux <maxence@maireaux.fr>
> Improve release docs

- pkg/storage/sqlstorage/migrations/postgresql/1.sql
- pkg/storage/sqlstorage/migrations/postgresql/4.sql
- pkg/storage/sqlstorage/migrations/postgresql/5.sql
Add a GIN index on 'postings' field of the 'transaction' table.
Change use_account function from plsql to pure sql (to be able to use index, and probably inline function).
> Optimize transactions read.

- .github/workflows/pr_open.yml
- .golangci.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- Makefile
Implement [Commit Conventional](https://www.conventionalcommits.org/en/v1.0.0/)
> feat: add commit style normalization

- .github/workflows/main.yml
> ci: Add Codecov in main branch

- .github/workflows/pr_open.yml
> ci: PR Name & Commit Style is not a blocker for all CI

- pkg/api/controllers/swagger.yaml
- pkg/api/controllers/transaction_controller.go
- pkg/api/controllers/transaction_controller_test.go
- pkg/storage/sqlstorage/pagination.go
- pkg/storage/sqlstorage/store_test.go
- pkg/storage/sqlstorage/transactions.go
- pkg/storage/transactions.go
This add the metadata filter on transactions list as the accounts endpoint.
* pkg/storage
* pkg/api
> feat: Add metadata filter on transactions list

- examples/jaeger-exporter/docker-compose.yml
- pkg/ledger/resolver.go
See embedded comments for an explanation.
The PR also embed a new docker-compose.yml example to use jaeger.
Setup dependencies
> fix: OpenTelemetry support on storage.

- .github/dependabot.yml 
- .github/workflows/main.yml
- .github/workflows/pr_open.yml
- .github/workflows/release.yml
- .goreleaser.yml
- Taskfile.yaml
- goreleaser.Dockerfile
> feat: Add support Linux in ARM64 & Improvement for CI 

- cmd/container.go
- go.mod
> feat: Disable segment feature for non released version

- .goreleaser.yml
> feat: Remove full changelog on docs

- .github/workflows/template_docker.yaml
> fix: Add UI in Docker Image

- pkg/storage/sqlstorage/collect.go
See https://github.com/golang/go/issues/44305
> fix: Fix embedded filesystem access

- pkg/core/log.go
- pkg/core/log_test.go
This PR add a "LogProcessor" struct.
Its role is to rebuild the expected the database view reading log from the database.
> feat: Add a log processor to compute the expected model reading logs.

- pkg/api/controllers/mapping_controller_test.go
- pkg/core/contract.go
- pkg/core/expr.go
- pkg/core/expr_test.go
- pkg/ledger/ledger.go
- pkg/ledger/ledger_test.go
- pkg/ledger/process.go
- pkg/storage/sqlstorage/store_ledger_test.go
Restore mapping removed from a previous PR.
- [] Refactoring / Technical debt
> feat: restore mapping

- pkg/api/controllers/transaction_controller_test.go
- pkg/core/asset.go
Allow assets to contains digits after first char.
> feat: Change assets format

- README.md
Signed-off-by: Hugo Hamon <hhamon@users.noreply.github.com>
> doc: links to formance.com instead of numary

- go.mod
- go.sum
Machine in v1.2.0 as a bug with big int.
> fix: Upgrade Machine

- pkg/api/apierrors/errors.go
- pkg/api/controllers/script_controller.go
- pkg/api/controllers/script_controller_test.go
- pkg/api/controllers/swagger.yaml
- script controller: conflict on reference
- storage conflict error code 409 instead of 503
> fix: backport v1.7.7

- pkg/storage/sqlstorage/driver.go
Just remember what ledgers has already been initialized and avoid sql queries.
> feat: keep in cache already created ledgers

- pkg/api/controllers/transaction_controller_test.go
- pkg/core/numscript.go
- pkg/ledger/error.go
> fix: negative balances not allowed even with mapping defined

- cmd/serve.go
- cmd/worker.go
- go.mod
- go.sum
- internal/controller/ledger/store.go
- internal/storage/bucket/migrations/28-logs-async-hash-procedure/notes.yaml
- internal/storage/bucket/migrations/28-logs-async-hash-procedure/up.sql
- internal/storage/driver/driver.go
- internal/storage/ledger/logs_test.go
- internal/storage/ledger/main_test.go
- internal/storage/module.go
- internal/storage/system/store.go
- internal/worker/async_block.go
- internal/worker/fx.go
- pkg/features/features.go
- pkg/testserver/worker.go
- test/e2e/app_logs_blocks_async_test.go
- test/e2e/app_multiple_instance_test.go
- tools/generator/go.sum
> feat: add sync block hash

- docs/api/README.md
- openapi.yaml
- openapi/v2.yaml
- pkg/client/.speakeasy/gen.lock
- pkg/client/.speakeasy/gen.yaml
- pkg/client/docs/models/components/v2ledger.md
- pkg/client/formance.go
- pkg/client/models/components/v2ledger.go
> feat: set id field of Ledger object (openapi) optional

- internal/storage/driver/driver.go
Improve performance of rollback detection by processing buckets concurrently using a worker pool. Added configurable parallel workers with a default of 100, and implemented error handling for multiple potential failures during the process.
> fix: parallelize bucket migration rollback detection

- internal/storage/driver/driver.go
This reverts commit a01d9a7ec20306d4523b6e5338c2a382d3ff4f3c.
> fix: Revert "feat: don't check all buckets on all health checks"

- internal/storage/driver/driver.go
This reverts commit 2082a08be08b0c076f7f7fe0ebedadfd36138b72.
> fix: Revert "feat: don't check all buckets on all health checks (#751)"

- internal/api/common/errors.go
- internal/api/common/middleware_resolver.go
- internal/api/v1/middleware_auto_create_ledger.go
- internal/api/v2/controllers_bulk.go
- internal/api/v2/controllers_ledgers_create.go
- internal/api/v2/controllers_logs_import.go
> feat: hide textual errors on internal server errors

- internal/storage/bucket/migrations/28-fix-pcv-missing-asset/up.sql
> fix: invalid migration

- .github/workflows/main.yml
Added Tailscale GitHub Action to workflow for enhanced secure networking during CI tasks, leveraging OAuth credentials and tags.
> ci: integrate Tailscale action for secure CI/CD networking

- .coderabbit.yaml
- internal/api/bulking/mocks_ledger_controller_test.go
- internal/api/common/middleware_resolver.go
- internal/api/common/mocks_ledger_controller_test.go
- internal/api/v1/mocks_ledger_controller_test.go
- internal/api/v2/controllers_logs_import.go
- internal/api/v2/mocks_ledger_controller_test.go
- internal/controller/ledger/controller.go
- internal/controller/ledger/controller_default.go
- internal/controller/ledger/controller_generated_test.go
- internal/controller/ledger/controller_with_cache.go
- internal/controller/ledger/controller_with_events.go
- internal/controller/ledger/controller_with_too_many_client_handling.go
- internal/controller/ledger/controller_with_traces.go
- internal/controller/ledger/store.go
- internal/controller/ledger/store_generated_test.go
- internal/controller/system/state_tracker.go
- internal/storage/ledger/adapters.go
- internal/storage/ledger/store.go
- test/e2e/api_ledgers_import_test.go
- test/e2e/app_lifecycle_test.go
- **test: add import test with error**
- **feat: remove sql transaction on imports**
> fix: make import not transactional

- internal/api/v2/common.go
- internal/api/v2/controllers_transactions_list_test.go
- test/e2e/api_transactions_list_test.go
> fix: pageSize not effective when a cursor is used

- internal/README.md
- internal/api/v2/controllers_accounts_list.go
- internal/api/v2/controllers_accounts_read.go
- internal/api/v2/controllers_balances.go
- internal/api/v2/controllers_logs_list.go
- internal/api/v2/controllers_transactions_create.go
- internal/api/v2/controllers_transactions_list.go
- internal/api/v2/controllers_transactions_read.go
- internal/api/v2/controllers_transactions_revert.go
- internal/api/v2/controllers_volumes.go
- internal/api/v2/views.go
- internal/api/v2/views_test.go
- internal/controller/ledger/controller_default_test.go
- internal/log.go
- internal/transaction.go
- internal/volumes.go
> feat: allow marshalling of big ints in string using a header

- go.mod
- go.sum
- tools/generator/go.mod
- tools/generator/go.sum
> chore: bump numscript version to 0.0.18

- Earthfile
- **feat: add some pagination options**
- **feat: devenvs**
> feat: devenvs
