ledger/ledger.go, ledger/query/cursor.go, storage/postgres/accounts.go, storage/postgres/aggregations.go, storage/postgres/metadata.go, storage/postgres/store.go, storage/postgres/transactions.go, storage/sqlite/accounts.go, storage/sqlite/aggregations.go, storage/sqlite/metadata.go, storage/sqlite/transactions.go, storage/storage.go
closes #63 
Can be tested by posting metadata to a transaction (using quickstart transaction data from README):
```sh
curl -X POST -H "Content-Type: application/json" http://localhost:3068/quickstart/transactions/0/metadata -d \
'{
"transaction-type": "driver-payout",
"ride-type": "standard"
}'
```
Checking db:
```
sqlite> select * from metadata;
meta_id  meta_target_type  meta_target_id  meta_key                  meta_value       timestamp
-------  ----------------  --------------  ------------------------  ---------------  -------------------------
0        transaction       0               transaction-type          "driver-payout"  2021-11-06T13:53:08-04:00
1        transaction       0               ride-type                 "standard"       2021-11-06T13:53:08-04:00
```
=> implement meta id and timestamp logic

pkg/api/controllers/account_controller.go, pkg/api/controllers/script_controller_test.go, pkg/api/controllers/transaction_controller.go, pkg/ledger/ledger.go, pkg/ledger/ledger_test.go, pkg/storage/accounts.go, pkg/storage/sqlstorage/accounts.go, pkg/storage/sqlstorage/accounts_test.go, pkg/storage/sqlstorage/aggregations.go, pkg/storage/sqlstorage/store_test.go, pkg/storage/sqlstorage/transactions.go, pkg/storage/transactions.go
As it was done, our query building didn't allow for multiple query parameters with the same name (even on different objects) being built easily. This PR aims to make the query building simpler, and more modular. It is done in two ways 
- All query building methods are removed, and a single builder (per db object) is in place to make the little checks and to fetch the necessary params
- No more map with string/interfaces. Since all of our params are known in advance, it makes more sense to use a defined struct, which is also easier to test.
Then, i did several tests using the API to list accounts and transactions, using some filters. I updated my db locally to test different cases, and always had an expected result. Please not that for these kind of tests to be useful, we should have a …
=> refactor(query): refactor the query building using structs and builders

cmd/container.go, cmd/doc.go, cmd/internal/env.go, cmd/internal/http_basic.go, cmd/internal/http_basic_test.go, cmd/root.go
It seems viper function RegisterAlias() does not works as expected, the GetStringSlice() function does not returns anything for any flag (the aliased as well as the alias).
So the fix consist of not using RegisterAlias() and simply handle both flags.
Also the PR move some bootstrap code from cmd/container.go and cmd/root.go inside package cmd/internal.
Now, all code related to http basic feature is located there.
- cmd/container.go
=> fix: Fix http basic flag.

sdk/templates/go/Taskfile.yml.mustache
Test already depends on vendor task, which already runs `go mod vendor`
Taskfile for Go SDK
=> chore: remove duplicate go mod vendor

pkg/api/controllers/pagination_test.go, pkg/storage/sqlstorage/transactions.go
=> fix: GET /transactions: pagination with token always returns a "previous" when moving backward, even on the first page

go.mod, go.sum
Upgrade the Numscript Machine to v1.1.2 to bring this fix: https://github.com/numary/machine/pull/31
The Numscript Machine
=> fix(numscript): upgrade machine to v1.1.2

.github/workflows/codeql.yml, .github/workflows/main.yml, .github/workflows/template_docker.yaml, .github/workflows/template_sdk-generate.yaml, .github/workflows/template_sdk-publish.yaml, sdk/templates/go/Taskfile.yml.mustache, sdk/templates/php/Taskfile.yml.mustache, sdk/templates/python/Taskfile.yml.mustache, sdk/templates/typescript/Taskfile.yml.mustache
=> fix: SDK Publisher

cmd/root.go, go.mod, go.sum, pkg/core/volumes.go, pkg/storage/sqlstorage/migrates/9-add-pre-post-volumes/any.go, pkg/storage/sqlstorage/migrates/9-add-pre-post-volumes/any_test.go, pkg/storage/sqlstorage/register.go
This PR add a migration to generate 'pre_commit_volumes' and 'post_commit_volumes' columns for 'transactions' table.
* pkg/storage/sqlstorage
=> feat: Add migration for pre/post commit volumes

pkg/storage/sqlstorage/log.go
When reading date from database, the sql driver set the local to the system local.
And when we compute the hash of a log (before database insertion), we are using the date as UTC.
=> fix: set logs as UTC when reading from database

pkg/ledger/ledger.go, pkg/ledger/ledger_test.go, pkg/ledger/process.go
Instead of handling conflict errors at store level (by interpreting error codes from the database server), we check potential reference conflict at core level.
=> feat: Change the order of UNSUFFICIENT_FUNDS and CONFLICT errors

pkg/api/controllers/swagger.yaml
Fix missing transaction timestamp in swagger specification.
=> fix: swagger tx timestamp

cmd/container.go, cmd/root.go, pkg/api/internal/testing.go, pkg/ledger/ledger.go, pkg/ledger/ledger_test.go, pkg/ledger/process.go, pkg/ledger/process_test.go, pkg/ledger/resolver.go
This PR adds a flag to be used in history ingestion scenario where we want to create transactions in the past. The existing timestamp over
The transaction commit validation system.
=> feat: add past timestamps flag

Dockerfile
This add wget to the generated image allowing health check of docker compose to run successfully.
=> fix: Add wget to generated image.

pkg/core/transaction.go, pkg/ledger/ledger.go
This fix error on revert event.
The field 'revertedTx' of the event was containing reverted tx instead of original postings, and the metadata indicating the revert was missing.
There are no test since a complete integration test branch is coming in a few days.
=> fix: revert event

pkg/api/controllers/swagger.yaml, pkg/api/controllers/transaction_controller_test.go, pkg/storage/sqlstorage/sqlite.go, pkg/storage/sqlstorage/store_ledger_test.go
Postgres is using ^{...}$ regex for its account filters, but not SQLite.
=> fix: SQLite: GetTransactions account filters should be a ^{...}$ regex

docker-compose.yml
It was executing `numary numary ui` whereas the correct command is `numary ui`
=> fix(docker-compose): cannot start control ui

go.sum, pkg/storage/sqlstorage/transactions.go
A previous PR had a new way to filter accounts which improved performances when querying the /transactions endpoint using 'source' and 'destination' filters.
This PR add the same mechanism for 'account' filter.
=> fix: 'account' filter on GET /transactions using old method

cmd/container.go, cmd/container_test.go, pkg/api/middlewares/lock.go, pkg/api/middlewares/module.go, pkg/api/middlewares/transaction.go, pkg/api/routes/routes.go, pkg/ledger/ledger.go, pkg/ledger/ledger_test.go, pkg/ledger/resolver.go, pkg/redis/lock.go, pkg/redis/module.go, pkg/storage/sqlstorage/transactions.go
Due to new idempotency feature, sql transactions has been moved at upper level (request).
So, the lock used by the ledger to lock writes was released before sql transaction commit.
This changes invert that by moving the ledger lock at api level.
=> fix: ledger lock

cmd/internal/analytics.go
Deprecated telemetry flag "segment-enabled" was enabled by default, causing telemetry used, even if flag "--telemetry-enabled" was set to false.
This change just set it to false.
=> fix(telemetry): deprecated flags enabled by default

pkg/api/controllers/transaction_controller_test.go, pkg/ledger/process.go, pkg/ledger/process_test.go
- the mapping check in ValidatePostings didn't work because the aggregator wasn't transferring volumes
- removed useless call to ValidatePostings in ProcessTxsData
- added a new overdraft test for Numscript
=> fix: Overdraft in single transactions execution path

pkg/api/controllers/transaction_controller_test.go, pkg/ledger/executor.go
Fixing a specific case where the payload of POST /transaction shouldn't be committed:
- no postings
- a script that hasn't any `send` instructions
=> fix: POST /transactions without any postings

pkg/api/controllers/account_controller.go, pkg/api/controllers/account_controller_test.go, pkg/api/controllers/balance_controller.go, pkg/api/controllers/balance_controller_test.go, pkg/api/controllers/info.go, pkg/api/controllers/ledger_controller.go, pkg/api/controllers/ledger_controller_test.go, pkg/api/controllers/mapping_controller.go, pkg/api/controllers/pagination_test.go, pkg/api/controllers/query.go, pkg/api/controllers/script_controller.go, pkg/api/controllers/script_controller_test.go, pkg/api/controllers/swagger.yaml, pkg/api/controllers/transaction_controller.go, pkg/api/controllers/transaction_controller_test.go, pkg/storage/sqlstorage/accounts.go, pkg/storage/sqlstorage/accounts_test.go, pkg/storage/sqlstorage/pagination.go
- deprecate `pagination_token` and add `cursor` query param
- deprecate `page_size` and add `pageSize` query param
- deprecate `start_time` and add `startTime` query param
- deprecate `end_time` and add `endTime` query param
- deprecate `balance_operator` and add `balanceOperator` query param
- fix {ledger}/_info response
- fix ScriptResponse duplicate details field
=> chore: Deprecate query params and switch to camelCase

cmd/root.go
The default configuration created by `numary config init` has UI and server using the same port. 
In docker-compose, UI uses port 3078
=> Fixes default UI port

pkg/storage/sqlstorage/transactions.go
=> fix(ledger): fix panic when checking last log

pkg/storage/sqlstorage/migrates/21-optimized-temporal/postgres.sql, pkg/storage/sqlstorage/transactions.go, pkg/storage/sqlstorage/transactions_test.go
This pull request introduces some improvements on temporal queries on transactions, by reviewing the way the `endTime` parameter is compiled.
We leverage the property on v1 stating that `∀A,B, (A.timestamp > B.timestamp) ⇒ (A.txid > B.txid)` to reduce the search space with an upper-bounded txid.
An index is added on the transactions table, to efficiently sort and query timestamps.
-----
Internal: Fixes ENG-573
=> feat: faster timestamp queries

pkg/api/controllers/account_controller.go, pkg/api/controllers/account_controller_test.go, pkg/api/controllers/swagger.yaml, pkg/ledger/storage.go, pkg/storage/sqlstorage/accounts.go, pkg/storage/sqlstorage/accounts_test.go
=> fix: duplicate entries on GET /accounts when filtering on balances

pkg/core/funding.go, pkg/ledger/execute_script_test.go, pkg/machine/vm/machine.go, pkg/machine/vm/machine_test.go
=> feat(machine): allow to send 0 amount

Earthfile
Use +sources stage in multiple targets for consistency and efficiency. Add go mod download step to sources stage to reduce redundancy. Remove redundant COPY commands to streamline stages.
=> refactor(Earthfile): reuse sources stage and optimize build process

cmd/serve.go, internal/api/common/pagination.go, internal/api/module.go, internal/api/router.go, internal/api/v2/common.go, internal/api/v2/controllers_accounts_list.go, internal/api/v2/controllers_accounts_list_test.go, internal/api/v2/controllers_ledgers_list.go, internal/api/v2/controllers_ledgers_list_test.go, internal/api/v2/controllers_logs_list.go, internal/api/v2/controllers_logs_list_test.go, internal/api/v2/controllers_transactions_list.go, internal/api/v2/controllers_transactions_list_test.go, internal/api/v2/controllers_volumes.go, internal/api/v2/controllers_volumes_test.go, internal/api/v2/query.go, internal/api/v2/routes.go, pkg/testserver/server.go, test/e2e/api_ledgers_list_test.go
=> feat(api): add configurable page sizes

Earthfile
Added a new task `openapi` to manage OpenAPI specification by copying `openapi.yaml` and saving it as an artifact. This enhances automation and ensures consistent handling of OpenAPI files.
=> feat: add task to handle OpenAPI artifact in Earthfile

internal/storage/bucket/migrations/18-transactions-fill-inserted-at/up.sql, internal/storage/bucket/migrations/19-transactions-fill-pcv/up.sql
- **fix: migration using azure postgres with no superuser provileges**
- **fix: next migration**
=> fix: migration postgres azure

cmd/serve.go, internal/controller/ledger/controller_default.go, internal/controller/ledger/numscript_parser.go, internal/controller/ledger/numscript_runtime.go, internal/controller/system/module.go, pkg/testserver/server.go
This PR allows to pass feature flags to the numscript interpreter (which is, in turn, under a feature flags)
Values must be comma-separated
The flags are ignored whenever `--experimental-numscript-interpreter is not passed`
For example:
```
--experimental-numscript-interpreter --numscript-interpreter-flags=experimental-oneof-combinator,experimental-if-expression
```
=> feat: added numscript feature flag

internal/api/bulking/bulker_test.go, internal/api/bulking/handler_stream_json.go, internal/api/bulking/handler_stream_json_test.go, internal/api/bulking/handler_stream_text.go, internal/api/bulking/handler_stream_text_test.go, internal/api/router.go, internal/api/v2/routes.go, test/e2e/api_bulk_test.go
=> feat: add json bulk stream

internal/storage/ledger/main_test.go, internal/storage/ledger/resource_volumes.go, internal/storage/ledger/volumes_test.go
=> feat: add first_usage filter on /volumes endpoint

internal/controller/ledger/controller_default.go, test/e2e/api_transactions_revert_test.go
Suppose we have three accounts:
`account_one` with balance 10
`account_two` with balance 0
`world`
If we create a transaction with postings
`account_one -5-> account_two`
`account_two -5-> world`
we will end up with final balances
`account_one` with balance 5
`account_two` with balance 0
`world`
When trying to revert this transaction, we will:
1. Get balances for destination accounts, in this case `account_one` and `account_two` [line 388]
2. Reverse our postings so our sources are `world` and `account_two` [line 395]
3. Iterating over postings, we will deduct `posting.Amount` from each of `world` and `account 2` [line 405]
4. Verify that all three accounts are non negative [line 415]
In this example, because `account_two` has no balance we will deduct `5` credits from it and end up with …
=> fix(ledger): tx reversion handles empty middle accounts

internal/storage/driver/driver.go
Improve performance of rollback detection by processing buckets concurrently using a worker pool. Added configurable parallel workers with a default of 100, and implemented error handling for multiple potential failures during the process.
=> fix: parallelize bucket migration rollback detection

internal/api/bulking/mocks_ledger_controller_test.go, internal/api/common/mocks_ledger_controller_test.go, internal/api/common/mocks_system_controller_test.go, internal/api/module.go, internal/api/v1/mocks_ledger_controller_test.go, internal/api/v1/mocks_system_controller_test.go, internal/api/v2/mocks_ledger_controller_test.go, internal/api/v2/mocks_system_controller_test.go, internal/controller/ledger/controller_generated_test.go, internal/controller/ledger/listener_generated_test.go, internal/controller/ledger/store_generated_test.go, internal/storage/driver/buckets_generated_test.go, internal/storage/driver/ledger_generated_test.go, internal/storage/driver/system_generated_test.go
=> fix(v2.2): fix version api field

internal/controller/ledger/controller_default.go, internal/controller/ledger/controller_default_test.go, internal/controller/ledger/store.go, internal/controller/ledger/store_generated_test.go, internal/storage/ledger/accounts_test.go, internal/storage/ledger/balances_test.go, internal/storage/ledger/moves_test.go, internal/storage/ledger/transactions.go, internal/storage/ledger/transactions_test.go, internal/storage/ledger/volumes_test.go
=> feat: remove one UPDATE sql query in case of metadata usage

internal/storage/ledger/accounts_test.go, internal/storage/ledger/resource_accounts.go
=> fix: inconsistent volumes on accounts list

docs/api/README.md, internal/controller/ledger/controller.go, internal/controller/ledger/controller_default.go, openapi.yaml, openapi/v2.yaml, pkg/client/.speakeasy/gen.lock, pkg/client/docs/models/components/runtime.md, pkg/client/models/components/v2posttransaction.go, test/e2e/api_transactions_create_test.go
Follow-up of this pr: https://github.com/formancehq/ledger/pull/878
changes the field name from "interpreter" to "experimental-interpreter"
=> feat: change runtime field name

internal/storage/ledger/paginator_column.go, internal/storage/ledger/paginator_offset.go, test/e2e/api_transactions_list_test.go
=> fix: pagination

internal/api/bulking/bulker.go, internal/api/v2/controllers_bulk.go, internal/api/v2/controllers_bulk_test.go, test/e2e/api_bulk_test.go
As the status code 400 is already used for partial errored response, I have used the error code 412.
Not beautiful but, no choice. 
If you want to suggest another code, I'm listening.
Fixes LX-55
=> fix(bulk): invalid status code (500) when using atomic + parallel

internal/api/v1/controllers_transactions.go, internal/api/v1/controllers_transactions_count_test.go, internal/api/v1/controllers_transactions_list_test.go
Fixes #491
- Add support for new `startTime` parameter as specified in OpenAPI v1.yaml
- Add support for new `endTime` parameter (similar issue)
- Maintain backward compatibility with deprecated `start_time`/`end_time`
- Fix incorrect database column reference from `date` to `timestamp`
- Query now correctly filters transactions by timestamp range
Changes:
- Support both camelCase (startTime/endTime) and snake_case (start_time/end_time) parameters
- Use correct `timestamp` column name matching database schema
- Prioritize new parameter names over deprecated ones
=> fix: support startTime/endTime parameters and correct database column

.envrc, .gitignore
This allows to source an optional and unversioned .envrc.local file which could be used to source secrets from 1Password:
```
source_url "https://github.com/tmatilai/direnv-1password/raw/v1.0.1/1password.sh" "sha256-4dmKkmlPBNXimznxeehplDfiV+CvJiIzg7H1Pik4oqY="
from_op GORELEASER_KEY=op://Shared/Goreleaser/password
```
=> chore(direnv): source .envrc.local if exists
